name: Build ISO
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

    steps:
      - name: Build
        id: build
        run: |
         # Set BUILD_DATE
         # 2022-09-29
         export BUILD_DATE=$(date +'%Y-%m-%d')
         
         echo "${{ secrets.SSH_PUBKEY }}" > builder-github.pub

         workdir=$(ssh -i builder-github.pub builder@falcon.repo.getcryst.al "mktemp -d")

         ssh -i builder-github.pub builder@falcon.repo.getcryst.al "cd $workdir && git clone https://github.com/crystal-linux/iso && cd iso && bash build.sh --build-iso"
         
         scp -i builder-github.pub builder@falcon.repo.getcryst.al:${workdir}/iso/*.iso builder@executor.repo.getcryst.al:/var/www/images/.

         # Set upload name to BUILD_DATE
         echo "::set-output name=date::${BUILD_DATE}"
         rm builder-github.pub # just to be sure
      - name: Upload 
        uses: ncipollo/release-action@v1
        with:
           desc: "See https://executor.repo.getcryst.al/images/"
           token: ${{ secrets.GITHUB_TOKEN }}
           tag: ${{ steps.build.outputs.date }}
    
           
