name: Build ISO
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
    container:
      image: crystallinux:crystal
      options: --privileged

    steps:
      - name: Build 
        run: |
         pacman -Syu --needed --noconfirm
         pacman -S --noconfirm --needed bind
         nslookup repo.getcryst.al
         pacman -S git archiso pacman-contrib --needed --noconfirm
         git clone https://github.com/crystal-linux/iso/
         cd iso
         bash build_iso.sh
         

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%g-%H-%M')"

      - name: Upload 
        uses: ncipollo/release-action@v1
        with:
           artifacts: "iso/*.iso"
           token: ${{ secrets.SECRET_TOKEN }}
           tag: ${{ steps.date.outputs.date }} 
        
           
